name: SWE Docs Patrol

on: 
  pull_request:
    branches:
      - develop
      - testing-ci
    paths:
      - 'esterni/**'
      - 'interni/**'
      - 'template/**'
      - '.github/**'

jobs:
  build_check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v1
    
    - name: Search and Compiles Latex Files
      uses: Jatus93/Latex-multicompiler@v1.0
      with:
        path_to_list: .github/filesToCompile
        artifact: false

    - name: Slack Notification
      uses: homoluctus/slatify@v2.0.1
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'CONTROLLO Pull Request'
        mention: 'here'
        mention_if: 'failure'
        channel: '#devops_documentazione'
        username: 'Docs Pull Request Patrol'
        url: ${{ secrets.SLACK_WEBHOOK }}
